# Generated by Django 3.0.8 on 2020-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200719_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='estmto',
            field=models.ManyToManyField(blank=True, to='api.Post'),
        ),
    ]
