# Generated by Django 3.0.8 on 2020-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200719_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='stars',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
