# Generated by Django 3.0.8 on 2020-07-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200719_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='profile',
            field=models.ManyToManyField(blank=True, to='api.Profile'),
        ),
    ]
