# Generated by Django 3.0.8 on 2020-07-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200719_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(choices=[('free', 'free'), ('premium', 'premium')], max_length=200, null=True)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
