# Generated by Django 3.0.8 on 2020-07-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200721_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='api.Profile'),
        ),
    ]
