# Generated by Django 3.0.8 on 2020-07-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200721_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='subtype',
            field=models.CharField(choices=[('free', 'free'), ('pro', 'pro'), ('premium', 'premium')], max_length=200, null=True),
        ),
    ]
