# Generated by Django 3.0.8 on 2020-07-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200722_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Coment'),
        ),
    ]
