# Generated by Django 3.0.8 on 2020-07-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_coment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Coment'),
        ),
    ]
