# Generated by Django 3.0.8 on 2020-07-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_postsrating_ratingstar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostsRating',
            new_name='PostsRatting',
        ),
        migrations.RenameModel(
            old_name='RatingStar',
            new_name='RattingStar',
        ),
    ]
