# Generated by Django 3.0.8 on 2020-07-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200722_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsratting',
            old_name='stars',
            new_name='star',
        ),
    ]
