# Generated by Django 3.0.8 on 2020-07-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200724_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='coment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Coment'),
        ),
    ]
