# Generated by Django 3.0.8 on 2020-08-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200802_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimation',
            old_name='stars',
            new_name='like',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='estmto',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='profile',
        ),
        migrations.AddField(
            model_name='estimation',
            name='profile1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileof', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='profile2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estmto', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='authority',
            field=models.ManyToManyField(related_name='estimations', through='api.Estimation', to='api.Profile', verbose_name='pricedProfiles'),
        ),
    ]
