# Generated by Django 3.0.8 on 2020-08-14 11:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200811_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, default='code_review.jpeg',
                                    null=True, upload_to=api.models.upload_profile_to),
        ),
    ]
